name: recallops
version: "1.0"
config-version: 2
profile: recallops
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  recallops:
    +materialized: table
